### ISSUE TITLE
INCORRECT SPELLING OF SUBSCRIBE.

### ISSUE THREAD

**Issue by AyomideWeb** [Grandida-Projects/reccoin-frontend#35]
![IMG_0409](https://github.com/Grandida-Projects/reccoin-frontend/assets/100292401/5d2e1a72-39b2-49c4-9392-422f1194a018)

**Comment by AyomideWeb** [comment]
@Inioluwajeremiah

**Comment by Inioluwajeremiah** [comment]
noted. thanks

**Comment by AyomideWeb** [comment]
Issue already addressed.

Good job guys.
